services:
  db:
    image: jacekbartlomiej/home-library-db
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    container_name: home-library-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  app:
    image: jacekbartlomiej/home-library
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-library
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src